--- #My Tasks Playbook
- hosts: webservers
  user: ansible
  become: yes
  tasks: 
    - name: Installing HTTPD on Nodes
      action: yum name=httpd state=installed
    - name: Installing mysql on Nodes
      action: yum name=mysql state=installed 
    - name: Installing tree on Nodes
      action: yum name=tree state=installed



